name: Deploy Databricks from Dev to Prod

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    name: Deploy notebooks and jobs to Prod
    runs-on: ubuntu-latest

    env:
      DEV_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
      DEV_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
      PROD_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      PROD_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install databricks-cli

      - name: Export from Dev
        run: |
          mkdir exported_notebooks
          databricks configure --token <<EOF
          $DEV_HOST
          $DEV_TOKEN
          EOF

          databricks workspace export_dir /Workspace/your_path_in_dev exported_notebooks

      - name: Import to Prod
        run: |
          databricks configure --token <<EOF
          $PROD_HOST
          $PROD_TOKEN
          EOF

          databricks workspace import_dir exported_notebooks /Workspace/your_path_in_prod --overwrite
