name: Deploy Databricks from Dev to Prod (New CLI)

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  deploy:
    name: Export from Dev and Import to Prod
    runs-on: ubuntu-latest

    env:
      DEV_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
      DEV_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
      PROD_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      PROD_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install new Databricks CLI
        run: pip install databricks

      - name: Export notebooks from Dev workspace
        run: |
          mkdir exported_notebooks
          databricks auth login --host "$DEV_HOST" --token "$DEV_TOKEN"
          databricks workspace export-dir \
            --source /Workspace/core
            --output exported_notebooks

      - name: Import notebooks to Prod workspace
        run: |
          databricks auth login --host "$PROD_HOST" --token "$PROD_TOKEN"
          databricks workspace import-dir \
            --input exported_notebooks \
            --target /Workspace/core
            --overwrite
