name: Deploy Databricks from Dev to Prod (New CLI)

on:
  push:
    branches:
      - main
  #workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_DEV_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
      DATABRICKS_DEV_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
      DATABRICKS_PROD_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_PROD_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Uninstall old CLI if any
        run: pip uninstall -y databricks-cli

      - name: Install new Databricks CLI
        run: pip install --upgrade databricks

      - name: Export notebooks from Dev workspace
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          mkdir exported_notebooks
          databricks workspace export-dir --source /Workspace/core

      - name: Import notebooks to Prod workspace
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        run: |
          databricks workspace import-dir --input exported_notebooks --target /Workspace/core
