name: Dev Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - name: Deploy Databricks Bundle
        run: databricks bundle deploy
        env:
          DATABRICKS_HOST: https://adb-3653682374616212.12.azuredatabricks.net/
          DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_DEV_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_job:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - name: Run Job
        run: databricks bundle run my-job
        env:
          DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_DEV_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
