name: Deploy Databricks from Dev to Prod (New CLI)

on:
  #push:
  #  branches:
     # - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Export notebooks from Dev workspace
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          pip install --upgrade databricks
          mkdir exported_notebooks
          databricks workspace export-dir --source /Workspace/core/

      - name: Import notebooks to Prod workspace
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        run: |
          pip install --upgrade databricks
          databricks workspace import-dir --input exported_notebooks --target /Workspace/core/
